[package]
name = "usb-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
dirs = "5.0.1"
env_logger = "0.10"
log = "0.4.20"
rusb = "0.9.3"
rust-ini = "0.20.0"
shellwords = "1.1.0"
